/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpscpu_LinearSolverMT */

#ifndef _Included_jpscpu_LinearSolverMT
#define _Included_jpscpu_LinearSolverMT
#ifdef __cplusplus
extern "C" {
#endif
#undef jpscpu_LinearSolverMT_SUPERLU_DRIVE_0
#define jpscpu_LinearSolverMT_SUPERLU_DRIVE_0 0L
#undef jpscpu_LinearSolverMT_SUPERLU_DRIVE_1
#define jpscpu_LinearSolverMT_SUPERLU_DRIVE_1 1L
#undef jpscpu_LinearSolverMT_MLP_DRIVE_CBC
#define jpscpu_LinearSolverMT_MLP_DRIVE_CBC 2L
#undef jpscpu_LinearSolverMT_MLP_DRIVE_SYM
#define jpscpu_LinearSolverMT_MLP_DRIVE_SYM 3L
/*
 * Class:     jpscpu_LinearSolverMT
 * Method:    solve0_mt
 * Signature: (III[D[I[I[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_jpscpu_LinearSolverMT_solve0_1mt
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray, jintArray, jintArray, jdoubleArray, jint);

/*
 * Class:     jpscpu_LinearSolverMT
 * Method:    solve1_mt
 * Signature: (III[D[I[I[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_jpscpu_LinearSolverMT_solve1_1mt
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray, jintArray, jintArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
